return {
  [1] = {
    ["q_id"] = 1,
    ["q_name"] = "角色",
    ["q_type"] = 1,
    ["q_order"] = 1,
    ["q_icon"] = "zjm_icon_a1.png",
    ["q_reqlvl"] = 1,
    ["q_reqtask"] = 0,
    ["q_hide"] = 0,
    ["q_link"] = "MAINUI_OPEN_PLAYER"
  },
  [2] = {
    ["q_id"] = 2,
    ["q_name"] = "锻造",
    ["q_type"] = 1,
    ["q_order"] = 2,
    ["q_icon"] = "zjm_icon_a2.png",
    ["q_reqlvl"] = 1,
    ["q_reqtask"] = 0,
    ["q_hide"] = 0,
    ["q_link"] = "MAINUI_OPEN_FORGE"
  },
  [3] = {
    ["q_id"] = 3,
    ["q_name"] = "预览",
    ["q_type"] = 1,
    ["q_order"] = 3,
    ["q_icon"] = "zjm_icon_a3.png",
    ["q_reqlvl"] = 1,
    ["q_reqtask"] = 0,
    ["q_hide"] = 0,
    ["q_link"] = "MAINUI_OPEN_PREVIEW"
  },
  [4] = {
    ["q_id"] = 4,
    ["q_name"] = "帮会",
    ["q_type"] = 1,
    ["q_order"] = 4,
    ["q_icon"] = "zjm_icon_a4.png",
    ["q_reqlvl"] = 1,
    ["q_reqtask"] = 0,
    ["q_hide"] = 0,
    ["q_link"] = "MAINUI_OPEN_GAME"
  },
  [5] = {
    ["q_id"] = 5,
    ["q_name"] = "商店",
    ["q_type"] = 1,
    ["q_order"] = 5,
    ["q_icon"] = "zjm_icon_a5.png",
    ["q_reqlvl"] = 1,
    ["q_reqtask"] = 0,
    ["q_hide"] = 0,
    ["q_link"] = "MAINUI_OPEN_SHOP"
  },
  [6] = {
    ["q_id"] = 6,
    ["q_name"] = "成就",
    ["q_type"] = 1,
    ["q_order"] = 6,
    ["q_icon"] = "zjm_icon_a6.png",
    ["q_reqlvl"] = 1,
    ["q_reqtask"] = 0,
    ["q_hide"] = 0,
    ["q_link"] = "MAINUI_OPEN_ACHIEVEMEN"
  },
  [7] = {
    ["q_id"] = 7,
    ["q_name"] = "神将",
    ["q_type"] = 1,
    ["q_order"] = 7,
    ["q_icon"] = "zjm_icon_a7.png",
    ["q_reqlvl"] = 1,
    ["q_reqtask"] = 0,
    ["q_hide"] = 0,
    ["q_link"] = "MAINUI_OPEN_HEAVENLY_GENERAL"
  },
  [8] = {
    ["q_id"] = 8,
    ["q_name"] = "图鉴",
    ["q_type"] = 1,
    ["q_order"] = 8,
    ["q_icon"] = "zjm_icon_a8.png",
    ["q_reqlvl"] = 1,
    ["q_reqtask"] = 0,
    ["q_hide"] = 0,
    ["q_link"] = "MAINUI_OPEN_LLLUSTATION"
  },
  [9] = {
    ["q_id"] = 9,
    ["q_name"] = "设置",
    ["q_type"] = 1,
    ["q_order"] = 9,
    ["q_icon"] = "zjm_icon_a9.png",
    ["q_reqlvl"] = 1,
    ["q_reqtask"] = 0,
    ["q_hide"] = 0,
    ["q_link"] = "MAINUI_OPEN_SETTIMG"
  },
  [10] = {
    ["q_id"] = 10,
    ["q_name"] = "合成",
    ["q_type"] = 1,
    ["q_order"] = 10,
    ["q_icon"] = "zjm_icon_a10.png",
    ["q_reqlvl"] = 1,
    ["q_reqtask"] = 0,
    ["q_hide"] = 0,
    ["q_link"] = "MAINUI_OPEN_FUSION"
  },
  [11] = {
    ["q_id"] = 11,
    ["q_name"] = "官职",
    ["q_type"] = 2,
    ["q_order"] = 1,
    ["q_icon"] = "zjm_icon_c1.png",
    ["q_reqlvl"] = 1,
    ["q_reqtask"] = 0,
    ["q_hide"] = 1,
    ["q_link"] = "MAINUI_OPEN_OFFICAL_POS"
  },
  [12] = {
    ["q_id"] = 12,
    ["q_name"] = "玩法",
    ["q_type"] = 2,
    ["q_order"] = 2,
    ["q_icon"] = "zjm_icon_c2.png",
    ["q_reqlvl"] = 1,
    ["q_reqtask"] = 0,
    ["q_hide"] = 1,
    ["q_link"] = "MAINUI_OPEN_DESCRIPTION"
  },
  [13] = {
    ["q_id"] = 13,
    ["q_name"] = "充值活动",
    ["q_type"] = 3,
    ["q_order"] = 1,
    ["q_icon"] = "zjm_icon_b1.png",
    ["q_reqlvl"] = 1,
    ["q_reqtask"] = 0,
    ["q_hide"] = 1,
    ["q_link"] = "MAINUI_OPEN_RECHARGE_ACTIVITY"
  },
  [14] = {
    ["q_id"] = 14,
    ["q_name"] = "运营活动",
    ["q_type"] = 3,
    ["q_order"] = 2,
    ["q_icon"] = "zjm_icon_b2.png",
    ["q_reqlvl"] = 1,
    ["q_reqtask"] = 0,
    ["q_hide"] = 1,
    ["q_link"] = "MAINUI_OPEN_OPERATION_ACTIVITY"
  },
  [15] = {
    ["q_id"] = 15,
    ["q_name"] = "日常活动",
    ["q_type"] = 3,
    ["q_order"] = 3,
    ["q_icon"] = "zjm_icon_b3.png",
    ["q_reqlvl"] = 1,
    ["q_reqtask"] = 0,
    ["q_hide"] = 1,
    ["q_link"] = "MAINUI_OPEN_DAILY_ACTIVITY"
  },
  [16] = {
    ["q_id"] = 16,
    ["q_name"] = "请神",
    ["q_type"] = 3,
    ["q_order"] = 4,
    ["q_icon"] = "zjm_icon_b4.png",
    ["q_reqlvl"] = 1,
    ["q_reqtask"] = 0,
    ["q_hide"] = 1,
    ["q_link"] = "MAINUI_OPEN_INVITIMG_GOD"
  },
  [17] = {
    ["q_id"] = 17,
    ["q_name"] = "竞技场",
    ["q_type"] = 3,
    ["q_order"] = 5,
    ["q_icon"] = "zjm_icon_b5.png",
    ["q_reqlvl"] = 1,
    ["q_reqtask"] = 0,
    ["q_hide"] = 1,
    ["q_link"] = "MAINUI_OPEN_ARENA"
  },
  [18] = {
    ["q_id"] = 18,
    ["q_name"] = "排行榜",
    ["q_type"] = 3,
    ["q_order"] = 6,
    ["q_icon"] = "zjm_icon_b6.png",
    ["q_reqlvl"] = 1,
    ["q_reqtask"] = 0,
    ["q_hide"] = 1,
    ["q_link"] = "MAINUI_OPEN_RANK"
  },
  [19] = {
    ["q_id"] = 19,
    ["q_name"] = "封神榜",
    ["q_type"] = 3,
    ["q_order"] = 7,
    ["q_icon"] = "zjm_icon_b7.png",
    ["q_reqlvl"] = 1,
    ["q_reqtask"] = 0,
    ["q_hide"] = 1,
    ["q_link"] = "MAINUI_OPEN_INVESTITURE_GOD"
  },
  [20] = {
    ["q_id"] = 20,
    ["q_name"] = "背包",
    ["q_type"] = 4,
    ["q_order"] = 1,
    ["q_icon"] = "zjm_icon_d1.png",
    ["q_reqlvl"] = 1,
    ["q_reqtask"] = 0,
    ["q_hide"] = 0,
    ["q_link"] = "MAINUI_OPEN_BAG"
  },
  [21] = {
    ["q_id"] = 21,
    ["q_name"] = "社交",
    ["q_type"] = 4,
    ["q_order"] = 2,
    ["q_icon"] = "zjm_icon_d2.png",
    ["q_reqlvl"] = 1,
    ["q_reqtask"] = 0,
    ["q_hide"] = 0,
    ["q_link"] = "MAINUI_OPEN_SOCIAL"
  }
}