return {
  [4001] = {
    ["q_id"] = 4001,
    ["name"] = "神之觉醒",
    ["color"] = "",
    ["tinyIcon"] = "titleicon01.png",
    ["appendLight"] = "",
    ["open"] = 1,
    ["type"] = 2,
    ["levelCond"] = "",
    ["effectTime"] = "",
    ["Attrs"] = "1,10;2,10;9,5;10,5",
    ["buff"] = "",
    ["description"] = "",
    ["describe_two"] = "",
    ["openCondition"] = "1,516001"
  },
  [4002] = {
    ["q_id"] = 4002,
    ["name"] = "神之主宰",
    ["color"] = "",
    ["tinyIcon"] = "titleicon02.png",
    ["appendLight"] = "",
    ["open"] = 1,
    ["type"] = 2,
    ["levelCond"] = "",
    ["effectTime"] = "",
    ["Attrs"] = "1,12;2,12;21,6;22,6",
    ["buff"] = "",
    ["description"] = "",
    ["describe_two"] = "",
    ["openCondition"] = "1,415001"
  },
  [4003] = {
    ["q_id"] = 4003,
    ["name"] = "圣之觉醒",
    ["color"] = "",
    ["tinyIcon"] = "titleicon03.png",
    ["appendLight"] = "",
    ["open"] = 1,
    ["type"] = 2,
    ["levelCond"] = "",
    ["effectTime"] = "",
    ["Attrs"] = "1,14;2,14;23,7;24,7",
    ["buff"] = "",
    ["description"] = "",
    ["describe_two"] = "",
    ["openCondition"] = "1,414001"
  },
  [4004] = {
    ["q_id"] = 4004,
    ["name"] = "王之觉醒",
    ["color"] = "",
    ["tinyIcon"] = "titleicon04.png",
    ["appendLight"] = "",
    ["open"] = 1,
    ["type"] = 2,
    ["levelCond"] = "",
    ["effectTime"] = "",
    ["Attrs"] = "1,14;2,14;23,7;24,7",
    ["buff"] = "",
    ["description"] = "",
    ["describe_two"] = "",
    ["openCondition"] = "1,413001"
  }
}