-- NAME: ActiveAwardRef
-- TIME: 2015.5.26-15:46:32
-- Generated By Editor


return {
	["ActiveAward01"] = { id = "ActiveAward01", Award = ";item_09104=2", ActivePoint = 20, },
	["ActiveAward02"] = { id = "ActiveAward02", Award = ";item_09106=1", ActivePoint = 40, },
	["ActiveAward03"] = { id = "ActiveAward03", Award = ";item_06406=1", ActivePoint = 60, },
	["ActiveAward04"] = { id = "ActiveAward04", Award = ";item_06406=1", ActivePoint = 80, },
	["ActiveAward05"] = { id = "ActiveAward05", Award = "Gold=10;item_06406=2", ActivePoint = 100, },
}
